----Ejercicio 1
-----A) CreamoS la tabla alumno

CREATE TABLE ALUMNO(ID_ALUMNO INTEGER PRIMARY KEY, NOMBRE VARCHAR2(80), SEMESTRE INTEGER);

-----B) INSERTAMOS LOS 5 REGISTROS

INSERT INTO ALUMNO VALUES(1,'ELDER ALVARADO',1);
INSERT INTO ALUMNO VALUES(2,'JUAN PEREZ',1);
INSERT INTO ALUMNO VALUES(3,'EDUARDO CAMPOS',1);
INSERT INTO ALUMNO VALUES(4,'ALEJANDRO MONTIEL',1);
INSERT INTO ALUMNO VALUES(5,'DANIELA ESCAMILLA',1);

SELECT * FROM ALUMNO;

-----C) CREACION DE CURSOR TIPO UPDATE

    DECLARE 
    CURSOR CUR_ALUMNOS IS SELECT * FROM ALUMNO FOR UPDATE OF SEMESTRE; --SEMESTRE ES EL NOBRE DE LA COLUMNA A ACTUALIZAR
    BEGIN 
    --- LOGICA DEL CURSOR, ES MUY SIMPLE 
    FOR REC IN CUR_ALUMNOS LOOP
        UPDATE ALUMNO SET SEMESTRE=2 WHERE CURRENT OF CUR_ALUMNOS;
      END LOOP;
    END;
    /
    
    SELECT * FROM ALUMNO;
    
----EJERCICIO 2

---CREAMOS LA TABLA MATERIA

CREATE TABLE MATERIA(ID_MATERIA INTEGER,
                     ID_ALUMNO INTEGER,
                     MATERIA VARCHAR2(80),
                     CALIFICACION FLOAT,
                     CONSTRAINT PK_ID_MATERIA PRIMARY KEY(ID_ALUMNO), 
                     CONSTRAINT FK_ID_ALUMNO FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO));
                     

-----GENERAMOS LA SECUENCIA

    CREATE SEQUENCE SEC_MATERIA
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;

---CREAMOS EL PROCEDIMIENTO

    CREATE OR REPLACE PROCEDURE GUARDAR_MATERIA(MY_ID_MATERIA OUT INTEGER, MY_ID_ALUMNO IN INTEGER, MY_MATERIA IN VARCHAR2, MY_CALIFICACION IN FLOAT)
    AS
    BEGIN
    SELECT SEC_MATERIA.NEXTVAL INTO MY_ID_ALUMNO FROM DUAL;
    INSERT INTO MATERIA VALUES(MY_ID_MATERIA, MY_ID_ALUMNO, MY_MATERIA, MY_CALIFICACION);
    END;
    /
    
------B) GENERAR UN BLOQUE PL_SQL QUE INSERTE CON UN CICLO FOR A TODOS LOS ALUMNOS EN LA TABLA ALUMNO PARA LAS MATERIAS: "BASE DE DATOS 2" & "INGENIERIA SISTEMAS"


    CREATE OR REPLACE PROCEDURE GENERAR_MATERIAS
    AS
    BEGIN
    FOR i IN 1...2 LOOP
        INSERT INTO MATERIA VALUES(i,x,'Base de Datos II',8.65);
    FOR x IN 1...5 LOOP
        INSERT INTO MATERIA VALUES(i,x,'Ingenieria Sistemas',8.65);
    END LOOP;
    END LOOP;
    END;
    /
    
--- EJECUTAMOS EL PROCEDIMIENTO

    BEGIN
    GENERAR_MATERIAS();
    END;
    /

SELECT * FROM MATERIA;
