-----A) CreamoS la tabla alumno

CREATE TABLE ALUMNO(ID_ALUMNO INTEGER PRIMARY KEY, NOMBRE VARCHAR2(80), SEMESTRE INTEGER);

-----B) INSERTAMOS LOS 5 REGISTROS

INSERT INTO ALUMNO VALUES(1,'ELDER ALVARADO',1);
INSERT INTO ALUMNO VALUES(2,'JUAN PEREZ',1);
INSERT INTO ALUMNO VALUES(3,'EDUARDO CAMPOS',1);
INSERT INTO ALUMNO VALUES(4,'ALEJANDRO MONTIEL',1);
INSERT INTO ALUMNO VALUES(5,'DANIELA ESCAMILLA',1);

SELECT * FROM ALUMNO;
