CREATE TABLE USUARIO_X(ID INTEGER PRIMARY KEY, 
                       NOMBRE VARCHAR2(40),
                       EDAD INTEGER);
                       
INSERT INTO USUARIO_X VALUES(1,'JUAN',40);
INSERT INTO USUARIO_X VALUES(2,'ANA',32);
INSERT INTO USUARIO_X VALUES(3,'PEDRO',27);
INSERT INTO USUARIO_X VALUES(4,'MARIA',30);

SELECT * FROM USUARIO_X;

---------------PRENDE LA CONSOLA DE DEPURACION 
SET SERVEROUTPUT ON;

-----DECLARACION DE LOS CURSORES


---Ejercicio #1
---GENERAR UN CURSOR SOBRE LA TABLA USUARIO_X QUE AL "VER" CADA REGISTRO IMPRIMA EL CAMPO "NOMMBRE" DE CADA REGISTRO

DECLARE
CURSOR cur_1 IS SELECT * FROM USUARIO_X;
BEGIN
--AQUI VIENE LA LOGICA DEL CURSOR
FOR FILA IN cur_1 LOOP
DBMS_OUTPUT.PUT_LINE('EL NOMBRE ACTUAL ES ' || FILA.NOMBRE);
END LOOP;
END;
/

--Ejercicio #2
--Generar un cursor que contenga una variable interna y que realice la siguiente operacion si la edad es estrictamente mayor a 30
--asignar sueldo_base un factor de 1.5 y si es menor, no asignar el factor donde sueldo _base=6000 pesos.

DECLARE 
CURSOR CUR_2 IS SELECT * FROM USUARIO_X;
SUELDO_BASE INTEGER;
BEGIN
-- INICIALIZAMOS EL SUELDO BASE
FOR FILA IN CUR_2 LOOP 
SUELDO_BASE:=6000;
IF FILA.EDAD >30 THEN
SUELDO_BASE:=SUELDO_BASE*1.5;
END IF;
DBMS_OUTPUT.PUT_LINE('EL SUELDO ES '||SUELDO_BASE || '  EDAD:' ||FILA.EDAD);
END LOOP;
END;
/