----Ejercicio 1
-----A) CreamoS la tabla alumno

CREATE TABLE ALUMNO(ID_ALUMNO INTEGER PRIMARY KEY, NOMBRE VARCHAR2(80), SEMESTRE INTEGER);

-----B) INSERTAMOS LOS 5 REGISTROS

INSERT INTO ALUMNO VALUES(1,'ELDER ALVARADO',1);
INSERT INTO ALUMNO VALUES(2,'JUAN PEREZ',1);
INSERT INTO ALUMNO VALUES(3,'EDUARDO CAMPOS',1);
INSERT INTO ALUMNO VALUES(4,'ALEJANDRO MONTIEL',1);
INSERT INTO ALUMNO VALUES(5,'DANIELA ESCAMILLA',1);

SELECT * FROM ALUMNO;

-----C) CREACION DE CURSOR TIPO UPDATE

    DECLARE 
    CURSOR CUR_ALUMNOS IS SELECT * FROM ALUMNO FOR UPDATE OF SEMESTRE; --SEMESTRE ES EL NOBRE DE LA COLUMNA A ACTUALIZAR
    BEGIN 
    --- LOGICA DEL CURSOR, ES MUY SIMPLE 
    FOR REC IN CUR_ALUMNOS LOOP
        UPDATE ALUMNO SET SEMESTRE=2 WHERE CURRENT OF CUR_ALUMNOS;
      END LOOP;
    END;
    /
    
    SELECT * FROM ALUMNO;
    
----EJERCICIO 2