---Ponemos primero el SET SERVEROUTPUT ON
SET SERVEROUTPUT ON;

--Agregams un bloque PL SQL
    DECLARE
     DIA CHAR(80);
     FECHA DATE;
    BEGIN
    --INICIALIZAMOS LOS CAMPOS CON LAS FUNCIONES SIGUIENTES
    FECHA:=SYSDATE;
    DIA:=TO_CHAR(SYSDATE, 'DD-MONTH-YYYY');--mes completo
   -- DIA:=TO_CHAR(SYSDATE, 'DD');--SOLO EL DIA
   -- DIA:=TO_CHAR(SYSDATE, 'MONTH');--SOLO EL MES
   -- DIA:=TO_CHAR(SYSDATE, 'HH');--SOLO LA HORA
   -- DIA:=TO_CHAR(SYSDATE, 'DAY');--SOLO EL DIA(MIERCOLES)
   -- DIA:=TO_CHAR(SYSDATE, 'SS');--SOLO LOS SEGUNDOS
   -- DIA:=TO_CHAR(SYSDATE, 'MIN');--SOLO LOS MINUTOS
    DBMS_OUTPUT.PUT_LINE('LA FECHA ES '||DIA);
    END;
    /
    
    --Ejercicio 1: Generar un disparador que impida que los usuarios se guarden el dia miercoles
    
    CREATE TABLE USUARIO_TIEMPO(ID INTEGER PRIMARY KEY,
                                NOMBRE VARCHAR2(80),
                                EDAD INTEGER);
                                
    CREATE OR REPLACE TRIGGER DISP_TIEMPO BEFORE INSERT ON USUARIO_TIEMPO FOR EACH ROW
    BEGIN
       DBMS_OUTPUT.PUT_LINE('EL DIA ES '||TO_CHAR(SYSDATE,'DAY'));
    IF UPPER(TO_CHAR(SYSDATE,'DAY'))=UPPER('MIÉRCOLES') THEN --UPPER TODO EN MAYUSCULA
    RAISE_APPLICATION_ERROR(-20000, 'NO PUEDES GUARDAR EN MIERCOLES');
    END IF;
    END;
    /
    INSERT INTO USUARIO_TIEMPO VALUES(14,'ELI',60);
    
    --Ejercicio 2:Generar un disparador que impida guardar en los segundos del 11 al 59 de cada minuto
    
    CREATE TABLE USUARIO_CHECADOR(NOMBRE VARCHAR2(80));
    SET SERVEROUTPUT ON;
    CREATE OR REPLACE TRIGGER DISP_CHECADOR BEFORE INSERT ON USUARIO_CHECADOR FOR EACH ROW
    BEGIN 
          DBMS_OUTPUT.PUT_LINE('LOS SEGUNDOS SON '||TO_CHAR(SYSDATE,'SS'));
    IF TO_CHAR(SYSDATE,'SS')>10 THEN 
    RAISE_APPLICATION_ERROR(-20000,'NO PUEDES CHECAR DE 11 SEG A 59 SEG');
    END IF;
    END;
    /
    INSERT INTO USUARIO_CHECADOR VALUES('ELDER');